# Generated by Django 4.1 on 2022-08-24 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="회사명")),
                ("country", models.CharField(max_length=20, verbose_name="국가")),
                ("region", models.CharField(max_length=20, verbose_name="지역")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=10, verbose_name="이름")),
            ],
        ),
        migrations.CreateModel(
            name="Employment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=50, verbose_name="채용포지션")),
                ("reward", models.IntegerField(verbose_name="채용보상금")),
                ("content", models.TextField(verbose_name="채용내용")),
                ("techstack", models.CharField(max_length=50, verbose_name="사용기술")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employments",
                        to="employment.company",
                        verbose_name="회사",
                    ),
                ),
            ],
        ),
    ]
